In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df =pd.read_csv('emails.csv')

In [6]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [8]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [9]:
df.drop_duplicates(inplace = True)

In [10]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [11]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [12]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# Seperate X & Y

In [13]:
x = df.text.values

In [14]:
y = df.spam.values

# split dataset

In [15]:
#Import libary
from sklearn.model_selection import train_test_split 

In [17]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size=0.2, random_state=1)

# Data Preprocessing

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv = CountVectorizer()
x_train=cv.fit_transform(xtrain)

In [22]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML Algprithm

In [23]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [24]:
x_test = cv.transform(xtest)

In [25]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
model.score(x_test,ytest)

0.9938542581211589

In [27]:
emails = ['hey i am looking for machine learning tutorial in bangali language','hey you win an iphone xii giveaway for free please do the survey']

In [29]:
cv.emails = cv.transform(emails)

In [30]:
model.predict(cv.emails)

array([0, 1], dtype=int64)